# Generated by Django 5.0.4 on 2024-05-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctordetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docname', models.CharField(max_length=200)),
                ('docspecification', models.CharField(max_length=200)),
                ('docemail', models.CharField(max_length=200)),
                ('docphoto', models.ImageField(upload_to='')),
            ],
        ),
    ]
