# Generated by Django 5.0.4 on 2024-05-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_appointments_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=12)),
                ('ptname', models.CharField(max_length=200)),
                ('ptemail', models.CharField(max_length=200)),
                ('ptmobile', models.CharField(max_length=200)),
                ('ptdoctor', models.CharField(max_length=200)),
                ('ptdate', models.CharField(max_length=200)),
                ('pttime', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='appointments',
        ),
    ]
